### ISSUE TITLE
Create frontend analyze section

### ISSUE THREAD

**Issue by hannahkamundson** [codefordenver/gsn#133]
This will probably change the "tables" pages to a component and then will involve more redux

**Comment by mariksolo** [comment]
Hello, I am interested in doing this issue. I think that in terms of general structure, this page should be organized by student so that you can see the data for each individual student over time. I think that good data to be graphed for now would be attendance (the number of absences per week), and grades. I believe people are working on adding this data to the details of each student, but I do not see it.
